metadata:
  name: experiment_17
  exp_dir: "/home/sotka/dev/diplomatiki/experiments"
data:
  datasets: 
  - coco14
  - mpii
  dataset_length: null 
model:
  type: HMR2
  gtshape: false
training:
  bs: 64
  lr: 0.0003
  cuda: true
  epochs: 100 #to be replaced with iterations
  checkpoint: null 