metadata:
  name: experiment_5
  exp_dir: "/home/sotka/dev/diplomatiki/experiments"
data:
  datasets: 
  - coco14
  - mpii
  dataset_length: null 
model:
  arch:
    gtshape: false
  training:
    lr: 3e-4
    bs: 64
    cuda: true
    epochs: 100 #to be replaced with iterations
    checkpoint: null 